#pragma once

#define KEY_RESERVED            0x00
#define KEY_ESC                 0x01
#define KEY_1                   0x02
#define KEY_2                   0x03
#define KEY_3                   0x04
#define KEY_4                   0x05
#define KEY_5                   0x06
#define KEY_6                   0x07
#define KEY_7                   0x08
#define KEY_8                   0x09
#define KEY_9                   0x0A
#define KEY_0                   0x0B
#define KEY_MINUS               0x0C
#define KEY_EQUAL               0x0D
#define KEY_BACKSPACE           0x0E
#define KEY_TAB                 0x0F
#define KEY_Q                   0x10
#define KEY_W                   0x11
#define KEY_E                   0x12
#define KEY_R                   0x13
#define KEY_T                   0x14
#define KEY_Y                   0x15
#define KEY_U                   0x16
#define KEY_I                   0x17
#define KEY_O                   0x18
#define KEY_P                   0x19
#define KEY_LEFTBRACE           0x1A
#define KEY_RIGHTBRACE          0x1B
#define KEY_ENTER               0x1C
#define KEY_LEFTCTRL            0x1D
#define KEY_A                   0x1E
#define KEY_S                   0x1F
#define KEY_D                   0x20
#define KEY_F                   0x21
#define KEY_G                   0x22
#define KEY_H                   0x23
#define KEY_J                   0x24
#define KEY_K                   0x25
#define KEY_L                   0x26
#define KEY_SEMICOLON           0x27
#define KEY_APOSTROPHE          0x28
#define KEY_GRAVE               0x29
#define KEY_LEFTSHIFT           0x2A
#define KEY_BACKSLASH           0x2B
#define KEY_Z                   0x2C
#define KEY_X                   0x2D
#define KEY_C                   0x2E
#define KEY_V                   0x2F
#define KEY_B                   0x30
#define KEY_N                   0x31
#define KEY_M                   0x32
#define KEY_COMMA               0x33
#define KEY_DOT                 0x34
#define KEY_SLASH               0x35
#define KEY_RIGHTSHIFT          0x36
#define KEY_KPASTERISK          0x37
#define KEY_LEFTALT             0x38
#define KEY_SPACE               0x39
#define KEY_CAPSLOCK            0x3A
#define KEY_F1                  0x3B
#define KEY_F2                  0x3C
#define KEY_F3                  0x3D
#define KEY_F4                  0x3E
#define KEY_F5                  0x3F
#define KEY_F6                  0x40
#define KEY_F7                  0x41
#define KEY_F8                  0x42
#define KEY_F9                  0x43
#define KEY_F10                 0x44
#define KEY_NUMLOCK             0x45
#define KEY_SCROLLLOCK          0x46
#define KEY_KP7                 0x47
#define KEY_KP8                 0x48
#define KEY_KP9                 0x49
#define KEY_KPMINUS             0x4A
#define KEY_KP4                 0x4B
#define KEY_KP5                 0x4C
#define KEY_KP6                 0x4D
#define KEY_KPPLUS              0x4E
#define KEY_KP1                 0x4F
#define KEY_KP2                 0x50
#define KEY_KP3                 0x51
#define KEY_KP0                 0x52
#define KEY_KPDOT               0x53

#define KEY_102ND               0x56
#define KEY_F11                 0x57
#define KEY_F12                 0x58
#define KEY_RO                  0x59
#define KEY_KPENTER             0x60
#define KEY_RIGHTCTRL           0x61
#define KEY_KPSLASH             0x62
#define KEY_SYSRQ               0x63
#define KEY_RIGHTALT            0x64
#define KEY_LINEFEED            0x65
#define KEY_HOME                0x66
#define KEY_UP                  0x67
#define KEY_PAGEUP              0x68
#define KEY_LEFT                0x69
#define KEY_RIGHT               0x6A
#define KEY_END                 0x6B
#define KEY_DOWN                0x6C
#define KEY_PAGEDOWN            0x6D
#define KEY_INSERT              0x6E
#define KEY_DELETE              0x6F
#define KEY_MACRO               0x70
#define KEY_MUTE                0x71
#define KEY_VOLUMEDOWN          0x72
#define KEY_VOLUMEUP            0x73
#define KEY_POWER               0x74
#define KEY_KPEQUAL             0x75
#define KEY_KPPLUSMINUS         0x76
#define KEY_PAUSE               0x77
#define KEY_SCALE               0x78

#define KEY_KPCOMMA             0x79
#define KEY_LEFTMETA            0x7D
#define KEY_RIGHTMETA           0x7E
#define KEY_COMPOSE             0x7F

#define KEY_STOP                0x80
#define KEY_AGAIN               0x81
#define KEY_PROPS               0x82
#define KEY_UNDO                0x83
#define KEY_FRONT               0x84
#define KEY_COPY                0x85
#define KEY_OPEN                0x86
#define KEY_PASTE               0x87
#define KEY_FIND                0x88
#define KEY_CUT                 0x89
#define KEY_HELP                0x8A
#define KEY_MENU                0x8B
#define KEY_CALC                0x8C
#define KEY_SETUP               0x8D
#define KEY_SLEEP               0x8E
#define KEY_WAKEUP              0x8F
#define KEY_FILE                0x90
#define KEY_SENDFILE            0x91
#define KEY_DELETEFILE          0x92
#define KEY_XFER                0x93
#define KEY_PROG1               0x94
#define KEY_PROG2               0x95
#define KEY_WWW                 0x96
#define KEY_MSDOS               0x97
#define KEY_COFFEE              0x98
#define KEY_SCREENLOCK          KEY_COFFEE
#define KEY_ROTATE_DISPLAY      0x99
#define KEY_DIRECTION           KEY_ROTATE_DISPLAY
#define KEY_CYCLEWINDOWS        0x9A
#define KEY_MAIL                0x9B
#define KEY_BOOKMARKS           0x9C
#define KEY_COMPUTER            0x9D
#define KEY_BACK                0x9E
#define KEY_FORWARD             0x9F
#define KEY_CLOSECD             0xA0
#define KEY_EJECTCD             0xA1
#define KEY_EJECTCLOSECD        0xA2
#define KEY_NEXTSONG            0xA3
#define KEY_PLAYPAUSE           0xA4
#define KEY_PREVIOUSSONG        0xA5
#define KEY_STOPCD              0xA6
#define KEY_RECORD              0xA7
#define KEY_REWIND              0xA8
#define KEY_PHONE               0xA9
#define KEY_ISO                 0xAA
#define KEY_CONFIG              0xAB
#define KEY_HOMEPAGE            0xAC
#define KEY_REFRESH             0xAD
#define KEY_EXIT                0xAE
#define KEY_MOVE                0xAF
#define KEY_EDIT                0xB0
#define KEY_SCROLLUP            0xB1
#define KEY_SCROLLDOWN          0xB2
#define KEY_KPLEFTPAREN         0xB3
#define KEY_KPRIGHTPAREN        0xB4
#define KEY_NEW                 0xB5
#define KEY_REDO                0xB6

#define KEY_F13                 0xB7
#define KEY_F14                 0xB8
#define KEY_F15                 0xB9
#define KEY_F16                 0xBA
#define KEY_F17                 0xBB
#define KEY_F18                 0xBC
#define KEY_F19                 0xBD
#define KEY_F20                 0xBE
#define KEY_F21                 0xBF
#define KEY_F22                 0xC0
#define KEY_F23                 0xC1
#define KEY_F24                 0xC2

#define KEY_PLAYCD              0xC8
#define KEY_PAUSECD             0xC9
#define KEY_PROG3               0xCA
#define KEY_PROG4               0xCB
#define KEY_ALL_APPLICATIONS    0xCC
#define KEY_DASHBOARD           KEY_ALL_APPLICATIONS
#define KEY_SUSPEND             0xCD
#define KEY_CLOSE               0xCE
#define KEY_PLAY                0xCF
#define KEY_FASTFORWARD         0xD0
#define KEY_BASSBOOST           0xD1
#define KEY_PRINT               0xD2
#define KEY_HP                  0xD3
#define KEY_CAMERA              0xD4
#define KEY_SOUND               0xD5
#define KEY_QUESTION            0xD6
#define KEY_EMAIL               0xD7
#define KEY_CHAT                0xD8
#define KEY_SEARCH              0xD9
#define KEY_CONNECT             0xDA
#define KEY_FINANCE             0xDB
#define KEY_SPORT               0xDC
#define KEY_SHOP                0xDD
#define KEY_ALTERASE            0xDE
#define KEY_CANCEL              0xDF
#define KEY_BRIGHTNESSDOWN      0xE0
#define KEY_BRIGHTNESSUP        0xE1
#define KEY_MEDIA               0xE2

#define KEY_SWITCHVIDEOMODE     0xE3
#define KEY_KBDILLUMTOGGLE      0xE4
#define KEY_KBDILLUMDOWN        0xE5
#define KEY_KBDILLUMUP          0xE6

#define KEY_SEND                0xE7
#define KEY_REPLY               0xE8
#define KEY_FORWARDMAIL         0xE9
#define KEY_SAVE                0xEA
#define KEY_DOCUMENTS           0xEB

#define KEY_BATTERY             0xEC

#define KEY_BLUETOOTH           0xED
#define KEY_WLAN                0xEE
#define KEY_UWB                 0xEF

#define KEY_UNKNOWN             0xF0

#define KEY_VIDEO_NEXT          0xF1
#define KEY_VIDEO_PREV          0xF2
#define KEY_BRIGHTNESS_CYCLE    0xF3
#define KEY_BRIGHTNESS_AUTO     0xF4
#define KEY_BRIGHTNESS_ZERO     KEY_BRIGHTNESS_AUTO
#define KEY_DISPLAY_OFF         0xF5

#define KEY_WWAN                0xF6
#define KEY_WIMAX               KEY_WWAN
#define KEY_RFKILL              0xF7

#define KEY_MICMUTE             0xF8
